---
- name: Create vector directory
  become: true
  ansible.builtin.file:
    path: "{{ vector_install_dir }}"
    state: directory
    mode: '0755'

- name: Download Vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/vector-{{ vector_version }}.tar.gz"
    mode: '0644'

- name: Extract Vector archive
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/vector-{{ vector_version }}.tar.gz"
    dest: "{{ vector_install_dir }}"
    remote_src: true
    extra_opts:
      - --strip-components=2

- name: Create Vector config directory
  become: true
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: '0755'

- name: Deploy Vector config
  become: true
  ansible.builtin.template:
    src: vector.yml.j2
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: '0644'
  notify: Restart vector service

- name: Create Vector systemd service
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: '0644'
  notify: Restart vector service

- name: Enable and start Vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    enabled: true
    state: started
    daemon_reload: true
